import * as admin from 'firebase-admin';
admin.initializeApp();

export { onRegistrationDeleted } from './waitlistPromotion';
export { registerToEvent } from './registerToEvent';
export { completeExpiredEvents } from './eventCompletion';
export { onEventUpdated } from './notificationTriggers';
export { acceptInvite } from './acceptInvite';
export { updateCenso } from './updateCenso';
export { syncVillageDenormalization } from './syncVillageDenormalization';
export { onOccupationProposalApproved } from './onOccupationProposalApproved';
export { requestJoinVillage } from './requestJoinVillage';
export { respondToJoinRequest } from './respondToJoinRequest';
export { requestOrganizeVillage } from './requestOrganizeVillage';
export { respondToOrganizerRequest } from './respondToOrganizerRequest';
export { moderateNewsPost } from './news/moderateNewsPost';
export { deleteNewsPost } from './news/deleteNewsPost';
export { setTrustedNewsAuthor } from './news/setTrustedNewsAuthor';
export { resolveNewsReport } from './news/resolveNewsReport';
export { syncNewsReactionCounts } from './news/syncNewsReactionCounts';
export { syncNewsCommentCount } from './news/syncNewsCommentCount';
